### ISSUE TITLE
Compilation into cache leads to ScriptCompilationException

### ISSUE THREAD

**Issue by bluerobotch** [scriptcs/scriptcs#1153]
I have a simple script  [HelloWorld.csx](https://gist.github.com/bluerobotch/32a067c9faeb3e6799aeb55ceeddd0e2), printing out Hello World to the console. 
When executing the script with caching enabled, a ScriptCompilationException is thrown and the script does not get executed. But the compiled assembly gets written to the .scriptcs_cache directory:

`scriptcs HelloWorld.csx -cache`
> ERROR: Script compilation failed. [ScriptCompilationException] Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

When issuing the same command a second time, the script executed properly from the cached assembly:

`scriptcs HelloWorld.csx -cache`
> Hello World

**Comment by bluerobotch** [comment]
I have this issue since updating from version 0.15.0 to 0.16.1

**Comment by filipw** [comment]
Thanks, I created a PR with a change that should fix this.
If you want you can build from my branch and check if it works for you.

**Comment by bluerobotch** [comment]
Thanks for the quick reply and fix.
